from __future__ import annotations

from copy import deepcopy

BASE = {
    "btn_fast_order": "⚡ Быстрый заказ",
    "btn_intercity_passenger": "🛣 Межгород",
    "btn_intercity_driver": "🛣 Межгород",
    "btn_profile": "👤 Профиль",
    "btn_wallet": "💰 Баланс",
    "btn_back": "⬅️ Назад",
    "btn_cancel": "❌ Отмена",
    "btn_cancel_order": "❌ Отменить",
    "btn_finish_order": "🏁 Завершить",
    "btn_arrived": "📍 На месте",
    "btn_accept": "✅ Принять",
    "btn_coming": "🚶 Выхожу",
    "btn_send_loc": "📍 Отправить геолокацию",
    "btn_become_driver": "🚕 Стать водителем",
    "become_driver": "🚕 Стать водителем",
    "btn_other_car": "🚗 Другая марка",
    "btn_other_model": "🚘 Другая модель",
    "btn_other_city": "🏙 Другой город",
    "btn_switch_role_to_passenger": "🎭 Перейти в режим пассажира",
    "btn_switch_role_to_driver": "🚖 Перейти в режим водителя",
    "dashboard": "📊 Dashboard",
    "users": "👥 Пользователи",
    "drivers": "🚕 Водители",
    "finance": "💳 Финансы",
    "orders": "🧾 Заказы",
    "moderation": "🛎 Модерация",
    "broadcast": "📢 Рассылка",
    "payments": "💳 Пополнения",
    "lookup": "🔎 Пользователь по ID",
    "feedback": "💬 Отзывы",
    "complaints": "⚠️ Жалобы",
    "admins": "🛡 Админы",
    "user_mode": "👤 Режим пользователя",
    "wallet_title": "Кошелёк",
    "current_balance": "Текущий баланс",
    "deposit_btn": "Пополнить",
    "topup_request_sent": "✅ Заявка на пополнение отправлена.",
    "balance_topup_approved": "✅ Пополнение подтверждено.",
    "balance_topup_rejected": "❌ Пополнение отклонено.",
    "verified": "Подтверждён",
    "on_moderation": "На модерации",
    "driver_status": "Статус водителя",
    "status": "Статус",
    "user_role": "Роль",
    "role_passenger": "Пассажир",
    "balance_label": "Баланс",
    "select_country": "Выберите страну:",
    "select_region": "Выберите область:",
    "select_city": "Выберите город:",
    "select_district_city": "Выберите район или город:",
    "reg_done": "✅ Регистрация завершена.",
    "username_required_guide": "Telegram → Настройки → Имя пользователя",
    "enter_brand": "Выберите марку автомобиля:",
    "enter_model": "Выберите модель автомобиля:",
    "enter_plate": "Введите номер автомобиля:",
    "plate_error": "Номер слишком короткий.",
    "enter_color": "Введите цвет автомобиля:",
    "select_cap": "Выберите вместимость автомобиля:",
    "photo_front": "Отправьте фото автомобиля спереди, чтобы номер был хорошо виден.",
    "photo_back": "Отправьте фото автомобиля сзади, чтобы номер был хорошо виден.",
    "photo_left": "Отправьте фото автомобиля слева.",
    "photo_right": "Отправьте фото автомобиля справа.",
    "photo_tech": "Личные документы для регистрации не требуются.",
    "photo_lic": "Личные документы для регистрации не требуются.",
    "photo_license": "Личные документы для регистрации не требуются.",
    "photo_out": "Отправьте фото автомобиля снаружи.",
    "photo_in": "Отправьте фото автомобиля внутри.",
    "driver_card_title": "Карта водителя",
    "copy_hint": "Номер можно скопировать.",
    "driver_card_label": "Карта водителя",
    "driver_data_copy_hint": "Данные карты можно скопировать.",
    "files_saved": "Файлы сохранены в защищённом виде.",
    "offer_details_btn": "Открыть детали",
    "admin_receipt_new": "🧾 Новая заявка на пополнение",
    "user_label": "Пользователь",
    "amount_label": "Сумма",
    "card_label": "Карта",
    "countries": {
        "uz": "Узбекистан",
        "tr": "Турция",
        "sa": "Саудовская Аравия",
    },
    "cities": {
        "uz": ["Ташкент", "Самарканд", "Бухара", "Андижан", "Фергана", "Наманган", "Нукус", "Карши", "Термез", "Навои", "Джизак", "Ургенч"],
        "tr": ["Стамбул", "Анкара", "Измир", "Анталья", "Бурса", "Адана", "Конья", "Газиантеп", "Мерсин", "Кайсери", "Эскишехир", "Трабзон"],
        "sa": ["Эр-Рияд", "Джидда", "Мекка", "Медина", "Даммам", "Таиф", "Табук", "Абха", "Хаиль", "Джизан", "Наджран", "Эль-Хубар"],
    },
    "currencies": {"uz": "UZS", "kz": "KZT", "tr": "TRY", "sa": "SAR"},
    "models": {
        "uz": {
            "Chevrolet": ["Cobalt", "Gentra", "Nexia", "Lacetti", "Malibu", "Tracker", "Damas"],
            "Kia": ["K5", "Sonet", "Sportage", "Carnival"],
            "Hyundai": ["Elantra", "Sonata", "Tucson", "Staria"],
            "Toyota": ["Corolla", "Camry", "Land Cruiser", "Hiace"],
            "Chery": ["Tiggo 7", "Tiggo 8"],
            "BYD": ["Song Plus", "Chazor", "Han"],
        },
        "tr": {
            "Fiat": ["Egea", "Doblo", "Fiorino"],
            "Renault": ["Clio", "Megane", "Taliant"],
            "Toyota": ["Corolla", "Camry", "Proace City"],
            "Volkswagen": ["Passat", "Caddy", "Transporter"],
            "Ford": ["Focus", "Tourneo Courier", "Transit"],
            "Hyundai": ["i20", "Elantra", "Tucson"],
        },
        "sa": {
            "Toyota": ["Camry", "Corolla", "Hiace", "Innova"],
            "Hyundai": ["Accent", "Sonata", "Staria", "H1"],
            "Kia": ["Cerato", "K5", "Carnival"],
            "Nissan": ["Sunny", "Altima", "Urvan"],
            "GMC": ["Yukon", "Terrain"],
            "Honda": ["Accord", "City", "CR-V"],
        },
    },
    "car_types": ["Эконом", "Комфорт", "Минивэн"],
    "time_now": "Сейчас",
    "class4_short": "До 4 мест",
    "class7_short": "До 7 мест",
    "vehicle_class_label": "Класс машины",
    "supported_classes_label": "Может принимать",
    "current_mode_label": "Текущий режим",
    "mode_driver_label": "Водитель",
    "mode_passenger_label": "Пассажир",
    "toggle_small_orders_enabled": "✅ Приём 4-местных заказов включён.",
    "toggle_small_orders_disabled": "🚫 Приём 4-местных заказов отключён.",
    "role_switched_to_passenger": "🎭 Вы переключились в режим пассажира.",
    "role_switched_to_driver": "🚖 Вы переключились в режим водителя.",
    "intercity_create_for_driver": "🚘 Создать маршрут",
    "intercity_create_for_passenger": "🙋 Создать заявку",
    "intercity_available_for_driver": "📋 Смотреть заявки",
    "intercity_available_for_passenger": "📋 Смотреть маршруты",
    "color_label": "Цвет",
}


def _clone(base: dict, **updates):
    value = deepcopy(base)
    value.update(updates)
    return value


MESSAGES = {
    'ru': BASE,
    'uz': _clone(BASE,
        btn_fast_order='⚡ Tez buyurtma',
        btn_intercity_passenger='🛣 Shaharlararo',
        btn_intercity_driver='🛣 Shaharlararo',
        btn_profile='👤 Profil',
        btn_wallet='💰 Balans',
        btn_back='⬅️ Orqaga',
        btn_cancel='❌ Bekor qilish',
        btn_cancel_order='❌ Bekor qilish',
        btn_finish_order='🏁 Yakunlash',
        btn_arrived='📍 Yetib keldim',
        btn_accept='✅ Qabul qilish',
        btn_coming='🚶 Chiqyapman',
        btn_send_loc='📍 Lokatsiyani yuborish',
        btn_become_driver='🚕 Haydovchi bo‘lish',
        btn_other_car='🚗 Boshqa marka', btn_other_model='🚘 Boshqa model', btn_other_city='🏙 Boshqa shahar',
        become_driver='🚕 Haydovchi bo‘lish',
        wallet_title='Hamyon',
        current_balance='Joriy balans',
        deposit_btn='To‘ldirish',
        select_country='Davlatni tanlang:',
        select_region='Viloyatni tanlang:',
        select_city='Shaharni tanlang:',
        select_district_city='Tuman yoki shaharni tanlang:',
        reg_done='✅ Ro‘yxatdan o‘tish yakunlandi.',
        username_required_guide='Telegram → Sozlamalar → Username',
        verified='Tasdiqlangan',
        on_moderation='Moderatsiyada',
        driver_status='Haydovchi holati',
        role_passenger='Yo‘lovchi',
        enter_brand='Avtomobil markasini tanlang:',
        enter_model='Avtomobil modelini tanlang:',
        enter_plate='Davlat raqamini kiriting:',
        plate_error='Raqam juda qisqa.',
        enter_color='Mashina rangini kiriting:',
        select_cap='Sig‘imni tanlang:',
        photo_front='Avtomobilni old tomondan yuboring, raqam aniq ko‘rinsin.',
        photo_back='Avtomobilni orqa tomondan yuboring, raqam aniq ko‘rinsin.',
        photo_left='Avtomobilni chap tomondan yuboring.',
        photo_right='Avtomobilni o‘ng tomondan yuboring.',
        photo_tech='Ro‘yxatdan o‘tish uchun shaxsiy hujjatlar talab qilinmaydi.',
        photo_lic='Ro‘yxatdan o‘tish uchun shaxsiy hujjatlar talab qilinmaydi.',
        photo_license='Ro‘yxatdan o‘tish uchun shaxsiy hujjatlar talab qilinmaydi.',
        photo_out='Mashina tashqi rasmini yuboring.',
        photo_in='Mashina ichki rasmini yuboring.',
        driver_card_title='Haydovchi kartasi',
        admin_receipt_new='🧾 Balans to‘ldirish arizasi',
        user_label='Foydalanuvchi',
        amount_label='Summa',
        card_label='Karta',
        countries={'uz': 'O‘zbekiston', 'tr': 'Turkiya', 'sa': 'Saudiya Arabistoni'},
        cities={'uz': ["Toshkent", "Samarqand", "Buxoro", "Andijon", "Farg‘ona", "Namangan", "Nukus", "Qarshi", "Termiz", "Navoiy", "Jizzax", "Urganch"], 'tr': ["Istanbul", "Anqara", "Izmir", "Antaliya", "Bursa", "Adana", "Konya", "Gaziantep", "Mersin", "Kayseri", "Eskishehir", "Trabzon"], 'sa': ["Riyod", "Jidda", "Makka", "Madina", "Dammam", "Toif", "Tabuk", "Abha", "Hail", "Jizan", "Najron", "Al Khobar"]},
        currencies={'uz': 'UZS', 'kz': 'KZT', 'tr': 'TRY', 'sa': 'SAR'},
        class4_short='4 o‘ringacha',
        class7_short='7 o‘ringacha',
        vehicle_class_label='Mashina klassi',
        supported_classes_label='Qabul qilishi mumkin',
        current_mode_label='Joriy rejim',
        mode_driver_label='Haydovchi',
        mode_passenger_label='Yo‘lovchi',
        toggle_small_orders_enabled='✅ 4 o‘rinli buyurtmalar qabul qilinadi.',
        toggle_small_orders_disabled='🚫 4 o‘rinli buyurtmalar o‘chirildi.',
        role_switched_to_passenger='🎭 Siz yo‘lovchi rejimiga o‘tdingiz.',
        role_switched_to_driver='🚖 Siz haydovchi rejimiga o‘tdingiz.',
        intercity_create_for_driver='🚘 Yo‘nalish yaratish',
        intercity_create_for_passenger='🙋 So‘rov yaratish',
        intercity_available_for_driver='📋 So‘rovlarni ko‘rish',
        intercity_available_for_passenger='📋 Yo‘nalishlarni ko‘rish',
    ),
    'en': _clone(BASE,
        btn_fast_order='⚡ Fast order', btn_intercity_passenger='🛣 Intercity', btn_intercity_driver='🛣 Intercity',
        btn_profile='👤 Profile', btn_wallet='💰 Wallet', btn_back='⬅️ Back', btn_cancel='❌ Cancel',
        btn_cancel_order='❌ Cancel', btn_finish_order='🏁 Finish', btn_arrived='📍 Arrived', btn_accept='✅ Accept', btn_coming='🚶 Coming',
        btn_send_loc='📍 Send location', btn_become_driver='🚕 Become a driver', btn_other_car='🚗 Other brand', btn_other_model='🚘 Other model', btn_other_city='🏙 Other city', become_driver='🚕 Become a driver',
        wallet_title='Wallet', current_balance='Current balance', deposit_btn='Top up',
        select_country='Select country:', select_region='Select region:', select_city='Select city:', select_district_city='Select district or city:',
        reg_done='✅ Registration completed.', username_required_guide='Telegram → Settings → Username', verified='Verified', on_moderation='On moderation',
        driver_status='Driver status', role_passenger='Passenger', enter_brand='Choose vehicle brand:', enter_model='Choose vehicle model:',
        enter_plate='Enter vehicle plate:', plate_error='Plate is too short.', enter_color='Enter vehicle color:', select_cap='Choose capacity:',
        photo_front='Send a front photo of the car with the plate clearly visible.', photo_back='Send a rear photo of the car with the plate clearly visible.', photo_left='Send a left-side photo of the car.', photo_right='Send a right-side photo of the car.', photo_tech='Personal documents are not required for registration.', photo_lic='Personal documents are not required for registration.', photo_license='Personal documents are not required for registration.',
        photo_out='Send exterior vehicle photo.', photo_in='Send interior vehicle photo.', driver_card_title='Driver card', admin_receipt_new='🧾 New top-up request',
        user_label='User', amount_label='Amount', card_label='Card', countries={'uz': 'Uzbekistan', 'tr': 'Turkey', 'sa': 'Saudi Arabia'},
        cities={'uz': ['Tashkent', 'Samarkand', 'Bukhara', 'Andijan', 'Fergana', 'Namangan', 'Nukus', 'Karshi', 'Termez', 'Navoi', 'Jizzakh', 'Urgench'], 'tr': ['Istanbul', 'Ankara', 'Izmir', 'Antalya', 'Bursa', 'Adana', 'Konya', 'Gaziantep', 'Mersin', 'Kayseri', 'Eskisehir', 'Trabzon'], 'sa': ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Taif', 'Tabuk', 'Abha', 'Hail', 'Jizan', 'Najran', 'Al Khobar']},
        class4_short='Up to 4 seats', class7_short='Up to 7 seats', vehicle_class_label='Vehicle class', supported_classes_label='Supported classes',
        current_mode_label='Current mode', mode_driver_label='Driver', mode_passenger_label='Passenger',
        toggle_small_orders_enabled='✅ 4-seat orders enabled.', toggle_small_orders_disabled='🚫 4-seat orders disabled.',
        role_switched_to_passenger='🎭 You switched to passenger mode.', role_switched_to_driver='🚖 You switched to driver mode.',
        intercity_create_for_driver='🚘 Create route', intercity_create_for_passenger='🙋 Create request', intercity_available_for_driver='📋 View requests', intercity_available_for_passenger='📋 View routes',
    ),
    'ar': _clone(BASE,
        btn_fast_order='⚡ طلب سريع', btn_intercity_passenger='🛣 بين المدن', btn_intercity_driver='🛣 بين المدن',
        btn_profile='👤 الملف الشخصي', btn_wallet='💰 المحفظة', btn_back='⬅️ رجوع', btn_cancel='❌ إلغاء', btn_cancel_order='❌ إلغاء',
        btn_finish_order='🏁 إنهاء', btn_arrived='📍 وصلت', btn_accept='✅ قبول', btn_coming='🚶 قادم', btn_send_loc='📍 إرسال الموقع',
        btn_become_driver='🚕 كن سائقًا', become_driver='🚕 كن سائقًا', btn_other_car='🚗 ماركة أخرى', btn_other_model='🚘 موديل آخر', btn_other_city='🏙 مدينة أخرى', wallet_title='المحفظة', current_balance='الرصيد الحالي', deposit_btn='شحن',
        select_country='اختر الدولة:', select_region='اختر المنطقة:', select_city='اختر المدينة:', select_district_city='اختر المدينة أو المنطقة:',
        reg_done='✅ اكتمل التسجيل.', username_required_guide='Telegram → Settings → Username', verified='موثّق', on_moderation='قيد المراجعة',
        driver_status='حالة السائق', role_passenger='راكب', enter_brand='اختر ماركة السيارة:', enter_model='اختر موديل السيارة:', enter_plate='أدخل رقم السيارة:',
        plate_error='رقم السيارة قصير جدًا.', enter_color='أدخل لون السيارة:', select_cap='اختر السعة:', photo_front='أرسل صورة السيارة من الأمام مع وضوح الرقم.', photo_back='أرسل صورة السيارة من الخلف مع وضوح الرقم.', photo_left='أرسل صورة السيارة من الجهة اليسرى.', photo_right='أرسل صورة السيارة من الجهة اليمنى.', photo_tech='لا نطلب مستندات شخصية للتسجيل.', photo_lic='لا نطلب مستندات شخصية للتسجيل.',
        photo_license='لا نطلب مستندات شخصية للتسجيل.', photo_out='أرسل صورة السيارة من الخارج.', photo_in='أرسل صورة السيارة من الداخل.', driver_card_title='بطاقة السائق',
        admin_receipt_new='🧾 طلب شحن جديد', user_label='المستخدم', amount_label='المبلغ', card_label='البطاقة',
        countries={'uz': 'أوزبكستان', 'tr': 'تركيا', 'sa': 'السعودية'},
        cities={'uz': ['طشقند', 'سمرقند', 'بخارى', 'أنديجان', 'فرغانة', 'نمنغان', 'نوكوس', 'قرشي', 'ترمذ', 'نافوي', 'جيزك', 'أورغنج'], 'tr': ['إسطنبول', 'أنقرة', 'إزمير', 'أنطاليا', 'بورصة', 'أضنة', 'قونية', 'غازي عنتاب', 'مرسين', 'قيصري', 'إسكي شهير', 'طرابزون'], 'sa': ['الرياض', 'جدة', 'مكة', 'المدينة', 'الدمام', 'الطائف', 'تبوك', 'أبها', 'حائل', 'جازان', 'نجران', 'الخبر']},
        class4_short='حتى 4 مقاعد', class7_short='حتى 7 مقاعد', vehicle_class_label='فئة السيارة', supported_classes_label='يمكنه قبول', current_mode_label='الوضع الحالي',
        mode_driver_label='سائق', mode_passenger_label='راكب', toggle_small_orders_enabled='✅ تم تفعيل طلبات 4 مقاعد.', toggle_small_orders_disabled='🚫 تم تعطيل طلبات 4 مقاعد.',
        role_switched_to_passenger='🎭 تم التحويل إلى وضع الراكب.', role_switched_to_driver='🚖 تم التحويل إلى وضع السائق.', intercity_create_for_driver='🚘 إنشاء مسار', intercity_create_for_passenger='🙋 إنشاء طلب', intercity_available_for_driver='📋 عرض الطلبات', intercity_available_for_passenger='📋 عرض المسارات',
    ),
}
