import type { AppLanguage } from './constants';

type Dict = Record<string, string>;

const ru: Dict = {
  appName: 'Intaxi', home: 'Главная', profile: 'Профиль', city: 'Город', intercity: 'Межгород', wallet: 'Баланс', support: 'Поддержка', admin: 'Админ', back: 'Назад', country: 'Страна', region: 'Область / регион', cityField: 'Город / район', chooseRegion: 'Выберите область', chooseCity: 'Выберите город / район',
  createOrder: 'Создать заказ', myOrders: 'Мои заказы', availableOffers: 'Доступные заказы', currentTrip: 'Текущая поездка', passengerMode: 'Режим пассажира', driverMode: 'Режим водителя',
  fromAddress: 'Адрес откуда', toAddress: 'Адрес куда', seats: 'Места', price: 'Цена', yourPrice: 'Ваша цена', recommendedPrice: 'Рекомендованная цена', useRecommendedPrice: 'Поставить рекомендованную цену', comment: 'Комментарий', writeComment: 'Дополнительная информация',
  status: 'Статус', loading: 'Загрузка...', noData: 'Пока нет данных', noOrders: 'Заказы не найдены', noOffers: 'Заказы не найдены', save: 'Сохранить', submit: 'Отправить', updatedSuccessfully: 'Изменения сохранены', operationFailed: 'Не удалось выполнить действие',
  driversSeen: 'Водителей увидели заказ', raisePrice: 'Повысить цену', raisePriceHint: 'Свободных водителей мало или текущая цена ниже ожидаемой.', searchStarted: 'Поиск водителей уже запущен и не останавливается.', tripDistance: 'Длина маршрута', distance: 'Расстояние', eta: 'ETA',
  driverOnline: 'Водитель online', driverRegister: 'Регистрация водителя', paymentMethods: 'Реквизиты', account: 'Аккаунт', donate: 'Поддержать проект', intercityLabel: 'Межгород', international: 'Международный', passportAlert: 'Проверьте наличие загранпаспорта',
  activeOrder: 'Активный заказ', activeTrip: 'Текущая поездка', searchingDriver: 'Ищем водителя', driverFoundPassenger: 'Водитель найден', driverFoundDriver: 'Вы приняли заказ', driverOnWayPassenger: 'Водитель в пути', driverOnWayDriver: 'Вы в пути к пассажиру', driverArrivedPassenger: 'Водитель прибыл', driverArrivedDriver: 'Вы прибыли к пассажиру', tripInProgressPassenger: 'Поездка идёт', tripInProgressDriver: 'Поездка выполняется', seenShort: 'вод.',
  intercityOffersTitle: 'Предложения', intercityPassengerHint: 'Укажите направление и смотрите маршруты водителей по вашему пути.', intercityDriverHint: 'Укажите направление и смотрите заявки пассажиров по вашему пути.', routeFilter: 'Фильтр маршрута', fromWhere: 'Откуда', toWhere: 'Куда', exampleFrom: 'Например: Ташкент', exampleTo: 'Например: Самарканд', passengerRoutesOnly: 'Пассажиру показываются только маршруты водителей по направлению.', driverRequestsOnly: 'Водителю показываются только заявки пассажиров по направлению.', noRouteOffers: 'По этому направлению пока нет активных предложений.', createRequest: 'Создать заявку', publishRoute: 'Опубликовать маршрут', requestKind: 'Заявка пассажира', routeKind: 'Маршрут водителя', acceptAsDriver: 'Принять как водитель', goAsPassenger: 'Поехать пассажиром', openOffer: 'Открыть предложение', accepting: 'Принимаем...', all: 'Все', requests: 'Заявки', routes: 'Маршруты', flexible: 'Гибко', date: 'Дата', time: 'Время', regularMode: 'Обычный режим', womenMode: 'Женский режим', unknownStatus: 'Неизвестный статус', unknownMode: 'Неизвестный режим', searchStatus: 'Идёт поиск', activeStatus: 'Активно', acceptedStatus: 'Принято', completedStatus: 'Завершено', cancelledStatus: 'Отменено', loadingOffers: 'Загрузка предложений...',
  driver: 'Водитель', driverAir: 'Эфир заказов', driverAirHint: 'Включите эфир, чтобы получать заказы по вашей зоне.', needDriverCheck: 'Нужна проверка водителя', driverCheckHint: 'После подтверждения профиля здесь появится полноценный выход в эфир.', applyDriver: 'Подать заявку', busy: 'Занят', free: 'Свободен', check: 'Проверка', ok: 'ОК', no: 'Нет', location: 'Локация', locationQuestion: 'Где принимать заказы?', locationHint: 'При включённом эфире геолокация обновляется автоматически.', locationNotUpdated: 'Геолокация не обновлена', refreshLocation: 'Обновить геолокацию', locating: 'Определяем...', countryCode: 'Код страны', online: 'В эфире', offline: 'Не в эфире', inTrip: 'В поездке', air: 'Эфир', youAreOnline: 'Вы сейчас в эфире', youAreOffline: 'Вы не в эфире', airHint: 'Когда эфир включён, водитель видит доступные заказы по своей зоне.', goOnline: 'Выйти в эфир', goOffline: 'Завершить эфир', cityAir: 'Эфир заказов', intercityAir: 'Заявки пассажиров', autoLocationOn: 'Автообновление геолокации включено', autoLocationOff: 'Автообновление геолокации выключено', locationError: 'Не удалось получить геолокацию', loadDriverStatusFailed: 'Не удалось загрузить статус водителя', changeStatusFailed: 'Не удалось изменить статус'
};

const uz: Dict = {
  appName: 'Intaxi', home: 'Bosh sahifa', profile: 'Profil', city: 'Shahar', intercity: 'Shaharlararo', wallet: 'Balans', support: 'Yordam', admin: 'Admin', back: 'Orqaga', country: 'Davlat', region: 'Viloyat / hudud', cityField: 'Shahar / tuman', chooseRegion: 'Viloyatni tanlang', chooseCity: 'Shahar / tumanni tanlang',
  createOrder: 'Buyurtma yaratish', myOrders: 'Mening buyurtmalarim', availableOffers: 'Mavjud buyurtmalar', currentTrip: 'Joriy safar', passengerMode: 'Yo‘lovchi rejimi', driverMode: 'Haydovchi rejimi',
  fromAddress: 'Qayerdan manzil', toAddress: 'Qayerga manzil', seats: 'Joylar', price: 'Narx', yourPrice: 'Sizning narxingiz', recommendedPrice: 'Tavsiya narx', useRecommendedPrice: 'Tavsiya narxni qo‘yish', comment: 'Izoh', writeComment: 'Qo‘shimcha ma’lumot',
  status: 'Holat', loading: 'Yuklanmoqda...', noData: 'Hozircha ma’lumot yo‘q', noOrders: 'Buyurtma topilmadi', noOffers: 'Buyurtma topilmadi', save: 'Saqlash', submit: 'Yuborish', updatedSuccessfully: 'O‘zgarishlar saqlandi', operationFailed: 'Amal bajarilmadi',
  driversSeen: 'Buyurtmani ko‘rgan haydovchilar', raisePrice: 'Narxni oshirish', raisePriceHint: 'Bo‘sh haydovchilar kam yoki narx past.', searchStarted: 'Haydovchi qidirish davom etmoqda.', tripDistance: 'Yo‘l masofasi', distance: 'Masofa', eta: 'Yetib kelish',
  driverOnline: 'Haydovchi online', driverRegister: 'Haydovchi ro‘yxati', paymentMethods: 'Rekvizitlar', account: 'Akkaunt', donate: 'Loyihani qo‘llab-quvvatlash', intercityLabel: 'Shaharlararo', international: 'Xalqaro', passportAlert: 'Xalqaro safarlar uchun pasportni tekshiring',
  activeOrder: 'Faol buyurtma', activeTrip: 'Joriy safar', searchingDriver: 'Haydovchi qidirilmoqda', driverFoundPassenger: 'Haydovchi topildi', driverFoundDriver: 'Buyurtmani qabul qildingiz', driverOnWayPassenger: 'Haydovchi yo‘lda', driverOnWayDriver: 'Yo‘lovchi tomon yo‘ldasiz', driverArrivedPassenger: 'Haydovchi yetib keldi', driverArrivedDriver: 'Yo‘lovchi yoniga yetib keldingiz', tripInProgressPassenger: 'Safar davom etmoqda', tripInProgressDriver: 'Safar bajarilmoqda', seenShort: 'hayd.',
  intercityOffersTitle: 'Takliflar', intercityPassengerHint: 'Yo‘nalishni kiriting va yo‘lingizdagi haydovchi marshrutlarini ko‘ring.', intercityDriverHint: 'Yo‘nalishni kiriting va yo‘lingizdagi yo‘lovchi buyurtmalarini ko‘ring.', routeFilter: 'Yo‘nalish filtri', fromWhere: 'Qayerdan', toWhere: 'Qayerga', exampleFrom: 'Masalan: Toshkent', exampleTo: 'Masalan: Samarqand', passengerRoutesOnly: 'Yo‘lovchiga faqat yo‘nalishdagi haydovchi marshrutlari ko‘rsatiladi.', driverRequestsOnly: 'Haydovchiga faqat yo‘nalishdagi yo‘lovchi buyurtmalari ko‘rsatiladi.', noRouteOffers: 'Bu yo‘nalishda hozircha faol taklif yo‘q.', createRequest: 'Buyurtma yaratish', publishRoute: 'Marshrut qo‘yish', requestKind: 'Yo‘lovchi buyurtmasi', routeKind: 'Haydovchi marshruti', acceptAsDriver: 'Haydovchi sifatida qabul qilish', goAsPassenger: 'Yo‘lovchi bo‘lib borish', openOffer: 'Taklifni ochish', accepting: 'Qabul qilinmoqda...', all: 'Barchasi', requests: 'Buyurtmalar', routes: 'Marshrutlar', flexible: 'Moslashuvchan', date: 'Sana', time: 'Vaqt', regularMode: 'Oddiy rejim', womenMode: 'Ayollar rejimi', unknownStatus: 'Noma’lum holat', unknownMode: 'Noma’lum rejim', searchStatus: 'Qidirilmoqda', activeStatus: 'Faol', acceptedStatus: 'Qabul qilingan', completedStatus: 'Yakunlangan', cancelledStatus: 'Bekor qilingan', loadingOffers: 'Takliflar yuklanmoqda...',
  driver: 'Haydovchi', driverAir: 'Buyurtmalar efiri', driverAirHint: 'Zonangizdagi buyurtmalarni olish uchun efirni yoqing.', needDriverCheck: 'Haydovchi tekshiruvi kerak', driverCheckHint: 'Profil tasdiqlangandan keyin to‘liq efir ochiladi.', applyDriver: 'Ariza yuborish', busy: 'Band', free: 'Bo‘sh', check: 'Tekshiruv', ok: 'OK', no: 'Yo‘q', location: 'Joylashuv', locationQuestion: 'Qayerda buyurtma qabul qilasiz?', locationHint: 'Efir yoqilganda geolokatsiya avtomatik yangilanadi.', locationNotUpdated: 'Geolokatsiya yangilanmagan', refreshLocation: 'Geolokatsiyani yangilash', locating: 'Aniqlanmoqda...', countryCode: 'Davlat kodi', online: 'Efirda', offline: 'Efirda emas', inTrip: 'Safarda', air: 'Efir', youAreOnline: 'Siz hozir efirdasiz', youAreOffline: 'Siz efirda emassiz', airHint: 'Efir yoqilganda haydovchi o‘z zonasidagi buyurtmalarni ko‘radi.', goOnline: 'Efirga chiqish', goOffline: 'Efirni tugatish', cityAir: 'Buyurtmalar efiri', intercityAir: 'Yo‘lovchi buyurtmalari', autoLocationOn: 'Geolokatsiya avtomatik yangilanmoqda', autoLocationOff: 'Geolokatsiya avtomatik yangilanmayapti', locationError: 'Geolokatsiyani olish imkoni bo‘lmadi', loadDriverStatusFailed: 'Haydovchi holatini yuklab bo‘lmadi', changeStatusFailed: 'Holatni o‘zgartirib bo‘lmadi'
};

export const messages: Record<AppLanguage, Dict> = {
  ru,
  uz,
  kz: { ...ru },
  en: { ...ru },
  ar: { ...ru, dir: 'rtl', currency: 'SAR' },
  tr: { ...ru },
};

export function normalizeLanguage(value?: string | null): AppLanguage {
  const v = value?.toLowerCase();
  if (v === 'uz' || v === 'kz' || v === 'en' || v === 'ar' || v === 'tr') return v as AppLanguage;
  return 'ru';
}

export function t(lang: string | undefined | null, key: string): string {
  const normalized = normalizeLanguage(lang);
  return messages[normalized][key] || messages.ru[key] || key;
}
